runtime: custom
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

endpoints_api_service:
  name: ENDPOINTS SERVICE-NAME # To be replaced.
  config_id: ENDPOINTS CONFIG-ID # To be replaced.
