openapi: 3.0.1
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/repeat:
    get:
      tags:
      - repeat-controller
      operationId: repeat
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: times
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
x-google-backend:
  protocol: h2
  address: <CLOUD_RUN_SERVICE_URL>
produces:
- application/json
host: <CLOUD_RUN_HOSTNAME>
schemes:
- https
