swagger: "2.0"
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
paths:
  /api/v1/repeat:
    get:
      tags:
      - repeat-controller
      operationId: repeat
      parameters:
      - name: text
        in: query
        required: true
        type: string
      - name: times
        in: query
        required: true
        type: integer
      responses:
        "200":
          description: OK
produces:
- application/json
x-google-backend:
  protocol: h2
  address: https://<YOUR_APP_URI_HERE>-ue.a.run.app/
schemes:
- https
host: <YOUR_HOST_HERE>-ue.a.run.app
