runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required, but ignored

# [START gae_flex_sendgrid_yaml]
gae_flex_sendgrid_yaml:
  SENDGRID_API_KEY: YOUR-SENDGRID-API-KEY
  SENDGRID_SENDER: YOUR-SENDGRID-SENDER
# [END gae_flex_sendgrid_yaml]
