options:
  env:
  - CNB_APP_DIR=/workspace
  - CNB_ANALYZED_PATH=/layers/analyzed.toml
  - CNB_BUILDPACKS_DIR=/cnb/buildpacks
  - CNB_GROUP_PATH=/layers/group.toml
  - CNB_LAYERS_DIR=/layers
  - CNB_PLAN_PATH=/layers/plan.toml
  - CNB_PLATFORM_DIR=/platform
  - CNB_PLATFORM_API=0.11
  - CNB_NO_COLOR=true
  - CNB_USER_ID=33
  - CNB_GROUP_ID=33
  - CNB_SKIP_RESTORE=true
  logging: LEGACY
  pool: {}
  substitutionOption: ALLOW_LOOSE
  volumes:
  - name: layers
    path: /layers
  - name: platform
    path: /platform
projectId: pratikshakapflex
queueTtl: 3600s
sourceProvenance: {}

steps:
- args:
  - --type=Manifest
  - --location=gs://staging.pratikshakapflex.appspot.com/ae/c645d4a2-4385-4ae7-9eb3-33a6c57bd162/manifest.json
  - --dest_dir=/workspace
  env:
  - GAE_APPLICATION_YAML_PATH=app.yaml
  id: fetch
  name: us.gcr.io/gae-runtimes/utilities/gcs-fetcher:base_20230416_18_04_RC00
- args:
  - us.gcr.io/pratikshakapflex/appengine/default.20230516t143631:c645d4a2-4385-4ae7-9eb3-33a6c57bd162
  entrypoint: /cnb/lifecycle/creator
  env:
  - CNB_RUN_IMAGE=us.gcr.io/gae-runtimes/buildpacks/google-gae-18/java/run:java_20230508_RC00
  - GAE_APPLICATION_YAML_PATH=app.yaml
  - X_GOOGLE_TARGET_PLATFORM=flex
  id: build
  name: gcr.io/pratikshakapflex/javanew:latest
- args:
  - --phase=post
  - --app_image_unique=us.gcr.io/pratikshakapflex/appengine/default.20230516t143631:c645d4a2-4385-4ae7-9eb3-33a6c57bd162
  - --app_image_stable=us.gcr.io/pratikshakapflex/appengine/default.20230516t143631:latest
  env:
  - GAE_APPLICATION_YAML_PATH=app.yaml
  id: post-buildpack
  name: us.gcr.io/gae-runtimes/utilities/buildpack-shim:base_20230416_18_04_RC00
substitutions:
  _GAE_APPLICATION_YAML_PATH: app.yaml
  _GOOGLE_DEBUG: 'true'
  _GOOGLE_LABEL_BUILDER_IMAGE: ugcr.io/pratikshakapflex/javanew
  _GOOGLE_LABEL_BUILDER_VERSION: latest
  _GOOGLE_LABEL_RUN_IMAGE: us.gcr.io/gae-runtimes/buildpacks/google-gae-18/java/run:java_20230508_RC00
  _GOOGLE_RUNTIME: java
  _GOOGLE_RUNTIME_VERSION: '11'
  _OUTPUT_IMAGE: us.gcr.io/pratikshakapflex/appengine/default.20230516t143631
  _X_GOOGLE_TARGET_PLATFORM: flex
  _ZEUS_SOURCE_LOCATION: https://storage.googleapis.com/staging.pratikshakapflex.appspot.com/ae/c645d4a2-4385-4ae7-9eb3-33a6c57bd162/manifest.json
  _ZEUS_SOURCE_TYPE: Manifest
tags:
- p-flex
- r-java
- s-STACK_GAE_18
- b-java_20230508_RC00
timeout: 600s
