runtime: java
env: flex
runtime_config:
  operating_system: ubuntu18
  runtime_version: 11
handlers:
- url: /.*
  script: this field is required, but ignored

# [START gae_flex_analytics_env_variables]
env_variables:
  GA_TRACKING_ID: YOUR-GA-TRACKING-ID
# [END gae_flex_analytics_env_variables]
