version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

#      - run:
#          name: Gecko Driver
#          command: curl -LO https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz && sudo tar -zxf geckodriver-*.tar.gz -C "${HOME}/bin"

      - run:
          name: backports
          command: sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe" && sudo apt-get update  && sudo apt-get install -t trusty-backports shellcheck

      - run:
          name: expect
          command: sudo apt-get install expect

      - run:
          name: service account
          command: openssl aes-256-cbc -d -in "${HOME}/${CIRCLE_PROJECT_REPONAME}/service-account.json.enc" -k "${key}" -iv "${iv}" -out "${HOME}/google-cloud-service-key.json" && export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/google-cloud-service-key.json"

  test:
    steps:
      - run:
        name: test script
        command: bash ./travis.sh && bash <(curl -s https://codecov.io/bash) # If successful, run code coverage
