runtime: java
env: flex
runtime_config:
  operating_system: ubuntu18 
# App Engine Flex will use the latest Java version on ubuntu18, i.e., Java 11.
handlers:
- url: /.*
  script: this field is required, but ignored

env_variables:
  BUCKET_NAME: YOUR-BUCKET-NAME
