version: "3"
services:
  livereload:
    image: demosite-livereload
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - "GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}"
      - "SITE_KEY=${SITE_KEY}"
      - "CHECKBOX_SITE_KEY=${CHECKBOX_SITE_KEY}"
    command: mvn spring-boot:run
    ports: [ "8080:8080" ]
    volumes:
    - "./:/app"
    restart: always
